services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  api-proxy:
    build: .
    ports:
      - "8002:8002"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
