services:
  mysql:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: userdb
      MYSQL_USER: useradmin
      MYSQL_PASSWORD: userpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d
    networks:
      - internal

  user-api:
    build: ./user-api
    ports:
      - "8000:8000"
    volumes:
      - ./user-api/app:/app/app
      - ./user-api/.env:/app/.env
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000 --log-level debug
    env_file:
      - ./user-api/.env
    depends_on:
      - jwt-api
      - mongo 
      - mysql
    networks:
      - internal

  mongo:
    image: mongo:6
    container_name: mongo-db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: mongopass
    ports:
      - "27017:27017"
    # volumes:
    #   - mongo_data:/data/db

  jwt-api:
    build: ./jwt-api
    volumes:
      - ./jwt-api/app:/app/app
      - ./jwt-api/.env:/app/.env
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8001 --log-level debug
    env_file:
      - ./jwt-api/.env
    networks:
      - internal
  
  api-proxy:
    build: ./aps
    ports:
      - "8002:8002"
    volumes:
      - ./aps/app:/app/app
      - ./aps/.env:/app/.env
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8002 --log-level debug
    env_file:
      - ./aps/.env
    depends_on:
      - mongo
    networks:   # we need to consider making this DB persistant for all replicas somehow.
      - internal 

  # strapi-brand-api:
  #   build: ./strapi
  #   container_name: brand-source-strapi
  #   ports:
  #     - "1337:1337"
  #   environment:
  #     NODE_ENV: development
  #     DATABASE_CLIENT: sqlite
  #   volumes:
  #     - ./strapi/source/somebrand:/app/app    #Mounts local code into container
  #   command: yarn develop
  #   restart: unless-stopped

volumes:
  mysql_data:
  mongo_data:

networks:
  internal:
    driver: bridge

